Repository eBay/figma-include-accessibility-annotations, pull requests merged in 2023-03, with the labels that each got.

#1 Fix: increase visual feedback of headings step
  src/code.js
  src/figma-code/steps/headings.js
  src/pages/Headings.js
Labels: enhancement

#2 Fixed New Page / Return to Dashboard Bug
  src/pages/ChooseYourOwnAdventure.js
Labels: bug, enhancement

#3 Update Readability and Lint
  src/code.js
  src/constants/contrast.js
  src/context/AppState.js
  src/context/index.js
  src/figma-code/onload-plugin.js
  src/figma-code/steps/color-contrast.js
Labels: documentation
